In [ ]:
#!git clone https://github.com/ngoxuanphong/GAME.git

Cloning into 'GAME'...
remote: Enumerating objects: 2564, done.
remote: Counting objects: 100% (639/639), done.
remote: Compressing objects: 100% (342/342), done.
remote: Total 2564 (delta 261), reused 522 (delta 240), pack-reused 1925
Receiving objects: 100% (2564/2564), 206.58 MiB | 31.41 MiB/s, done.
Resolving deltas: 100% (1064/1064), done.


In [1]:
%cd /Users/trancatkhanh/Downloads/GAME

/Users/trancatkhanh/Downloads/GAME


# Tiến hành làm bài tập 1

**Bài tập 1 :**

In [ ]:
@njit()
def p0(state,per):
  # Choose an action
  actions = getValidActions(state)
  actions = np.where(actions == 1)[0]
  action = actions[np.random.randint(len(actions))]

  # Save the state in per[0] done 
  if per[3][0] == 0 :
    for i in range(len(state)):
      per[0][i] = state[i]
    per[3][0] +=1
    
  elif per[3][0] == 1:
    for i in range(len(state)):
        per[1][i] = np.minimum(per[0],state)[i]
        per[2][i] = np.maximum(per[0],state)[i]
    per[3][0] +=1
  else:
    for i in range(len(state)):
        per[1][i] = np.minimum(per[1],state)[i]
        per[2][i] = np.maximum(per[2],state)[i]

  # Create an array of -1,0,-1
  if getReward(state) == 1 :
    per[4][0] += 1
    if per[4][0]> 5000 :
      for i in range(len(state)):
        per[0][i] = state[i]
      for i in range(len(state)):
        per[0][i] = per[1][i]
        if getReward(per[0]) <= 0 :
          per[5][i] = -1
        per[0][i] = per[2][i]
        if getReward(per[0]) <= 0 :
          per[5][i] = -1
        per[0][i] = state[i]
        
  elif getReward(state) == 0 :
    per[4][0] += 1
    if per[4][0]> 5000 :
      for i in range(len(state)):
        per[0][i] = state[i]
      for i in range(len(state)):
        per[0][i] = per[1][i]
        if getReward(per[0]) == 1 :
          per[5][i] = 1
        per[0][i] = per[2][i]
        if getReward(per[0]) == 1  :
          per[5][i] = 1
        per[0][i] = state[i]
  # Change the value of array to 1 or -1
  if per[4][0]> 100 and per[4][0]<9900:
    for i in range(len(state)):
      if per[5][i]!=0:
        per[5][i] = per[5][i] / np.abs(per[5][i])
  return action,per




#0 : Save previous state
#1 : Save min state
#2 : Save max state
#3 : Save number of game
#5 : Save the array decide which index is -1 , 0, 1

# Check tất cả các game bài tập 1 




**Check Game Splendor_v3**

In [ ]:
import numpy as np
from base.Splendor_v3.env import *
perx = [np.full(getStateSize(),0),np.full(getStateSize(),0),np.full(getStateSize(),0),np.full(getStateSize(),0),np.full(getStateSize(),0),np.full(getStateSize(),0)]
          #0                            #1                       #2                       #3                      #4                          #5
win, x = numba_main_2(p0, 10000,perx , 0)
# Print the array decide which index is -1 , 0, 1
print(x[5])
# Print the index == 1
print('benefit',np.where(x[5]==1))
# Print the index == -1
print('negative',np.where(x[5]==-1))

[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  1  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0 -1 -1 -1  0  0  0  0  0]
benefit (array([17]),)
negative (array([153, 154, 155]),)


 **Check game TLMN_v2**

In [ ]:
import numpy as np
from base.TLMN_v2.env import *
perx = [np.full(getStateSize(),0),np.full(getStateSize(),0),np.full(getStateSize(),0),np.full(getStateSize(),0),np.full(getStateSize(),0),np.full(getStateSize(),0)]
          #0                            #1                       #2                       #3                      #4                          #5
win, x = numba_main_2(p0, 10000,perx , 0)
# Print the array decide which index is -1 , 0, 1
print(x[5])

# Print the index == 1
print('benefit',np.where(x[5]==1))
# Print the index == -1
print('negative',np.where(x[5]==-1))



2521


**Check Game TLMN**

In [ ]:
import numpy as np
from base.TLMN.env import *
perx = [np.full(getStateSize(),0),np.full(getStateSize(),0),np.full(getStateSize(),0),np.full(getStateSize(),0),np.full(getStateSize(),0),np.full(getStateSize(),0)]
          #0                            #1                       #2                       #3                      #4                          #5
win, x = numba_main_2(p0, 50000,perx , 0)
# Print the array decide which index is -1 , 0, 1
print(x[5])

# Print the index == 1
print('benefit',np.where(x[5]==1))
# Print the index == -1
print('negative',np.where(x[5]==-1))

12319


**Check Game SushiGO**

In [ ]:
import numpy as np
from base.SushiGo.env import *
perx = [np.full(getStateSize(),0),np.full(getStateSize(),0),np.full(getStateSize(),0),np.full(getStateSize(),0),np.full(getStateSize(),0),np.full(getStateSize(),0)]
          #0                            #1                       #2                       #3                      #4                          #5
win, x = numba_main_2(p0, 10000,perx , 0)
# Print the array decide which index is -1 , 0, 1
print(x[5])

# Print the index == 1
print('benefit',np.where(x[5]==1))
# Print the index == -1
print('negative',np.where(x[5]==-1))

: 

: 

**Check MachiKoro**

In [ ]:
import numpy as np
from base.MachiKoro.env import *
perx = [np.full(getStateSize(),0),np.full(getStateSize(),0),np.full(getStateSize(),0),np.full(getStateSize(),0),np.full(getStateSize(),0),np.full(getStateSize(),0)]
          #0                            #1                       #2                       #3                      #4                          #5
win, x = numba_main_2(p0, 10000,perx , 0)
# Print the array decide which index is -1 , 0, 1
print(x[5])

# Print the index == 1
print('benefit',np.where(x[5]==1))
# Print the index == -1
print('negative',np.where(x[5]==-1))

2515


**Check Game Splendor**

In [ ]:
import numpy as np
from base.Splendor.env import *
perx = [np.full(getStateSize(),0),np.full(getStateSize(),0),np.full(getStateSize(),0),np.full(getStateSize(),0),np.full(getStateSize(),0),np.full(getStateSize(),0)]
          #0                            #1                       #2                       #3                      #4                          #5
win, x = numba_main_2(p0, 10000,perx , 0)
# Print the array decide which index is -1 , 0, 1
print(x[5])

# Print the index == 1
print('benefit',np.where(x[5]==1))
# Print the index == -1
print('negative',np.where(x[5]==-1))

**Check Game Splendor_v2**

In [ ]:
import numpy as np
from base.Splendor_v2.env import *
perx = [np.full(getStateSize(),0),np.full(getStateSize(),0),np.full(getStateSize(),0),np.full(getStateSize(),0),np.full(getStateSize(),0),np.full(getStateSize(),0)]
          #0                            #1                       #2                       #3                      #4                          #5
win, x = numba_main_2(p0, 10000,perx , 0)
# Print the array decide which index is -1 , 0, 1
print(x[5])

# Print the index == 1
print('benefit',np.where(x[5]==1))
# Print the index == -1
print('negative',np.where(x[5]==-1))

Game Sheriff

In [ ]:
import numpy as np
from base.Sheriff.env import *
perx = [np.full(getStateSize(),0),np.full(getStateSize(),0),np.full(getStateSize(),0),np.full(getStateSize(),0),np.full(getStateSize(),0),np.full(getStateSize(),0)]
          #0                            #1                       #2                       #3                      #4                          #5
win, x = numba_main_2(p0, 10000,perx , 0)
# Print the array decide which index is -1 , 0, 1
print(x[5])

# Print the index == 1
print('benefit',np.where(x[5]==1))
# Print the index == -1
print('negative',np.where(x[5]==-1))

Game Century

In [ ]:
import numpy as np
from base.Century.env import *
perx = [np.full(getStateSize(),0),np.full(getStateSize(),0),np.full(getStateSize(),0),np.full(getStateSize(),0),np.full(getStateSize(),0),np.full(getStateSize(),0)]
          #0                            #1                       #2                       #3                      #4                          #5
win, x = numba_main_2(p0, 10000,perx , 0)
# Print the array decide which index is -1 , 0, 1
print(x[5])

# Print the index == 1
print('benefit',np.where(x[5]==1))
# Print the index == -1
print('negative',np.where(x[5]==-1))

# Tiến hành bài tập 2
Bằng 1 code, train array value thành các giá trị trong khoảng từ -1 đến 1


Sao cho khi tính giá trị trung bình của np.sum(state endgame * value) (trong 100 trận), thì agent mạnh nhất luôn có giá trị cao nhất. (Làm để áp dụng với mọi game)

**Bước 1** :Tìm 5 con agent mạnh nhất

In [9]:
from base.Splendor_v3.env import *
@njit()
def p0(state,per):
    if per[3][0][0] == 0:
        a = per[2][0]
        b = per[1][0]
        choice = np.where(a+b < 10000)[0][0]
        per[3][0][0] = choice

    idmt = int(per[3][0][0])
    mt = per[0][idmt]
    actions = getValidActions(state)
    actions *= mt
    action = np.argmax(actions)
    if getReward(state) == 1:
        per[1][0][idmt] += 1
        per[3][0][0] = 0
    if getReward(state) == 0:
        per[2][0][idmt] += 1
        per[3][0][0] = 0
    return action,per



perx1 = [np.array([np.random.rand(getActionSize()) for _ in range(5)]),np.zeros((1,5)),np.zeros((1,5)),np.zeros((1,100))]
win, x1 = numba_main_2(p0,  50000,perx1 ,0)
# in số trận thắng
print(x1[1])
# in số trận thua
print(x1[2])
# lưu các con agent
l1 = x1[0][0]
l2 = x1[0][1]
l3 = x1[0][2]
l4 = x1[0][3]
l5 = x1[0][4]
import numpy as np
# Print the rank of agent based on win rate
print(x1[1]+x1[2])
print(np.argsort(x1[1]/(x1[1]+x1[2])))
print(x1[1]/(x1[1]+x1[2]))

[[2763. 2806. 4316. 2945. 2905.]]
[[7237. 7194. 5684. 7055. 7095.]]
[[10000. 10000. 10000. 10000. 10000.]]
[[0 1 4 3 2]]
[[0.2763 0.2806 0.4316 0.2945 0.2905]]


**Bước 2** : Tìm số lần xuất hiện giá trị max và min của index value 1 và -1 trong state


**Bước 3** : Sử dụng giá trị đó để tạo ra array value từ -1 đến 1


**Bước 4** : Check xem giá trị của state_end_game * array value có lớn nhất không 


In [97]:
from base.Splendor_v3.env import *


@njit()
def p0(state,per):
  # Choose an action
  actions = getValidActions(state)
  actions *= l1
  action = np.argmax(actions)

  # Save the state in per[0] done 
  if per[3][0] == 0 :
    for i in range(len(state)):
      per[0][i] = state[i]
    per[3][0] +=1
    
  elif per[3][0] == 1:
    for i in range(len(state)):
        per[1][i] = np.minimum(per[0],state)[i]
        per[2][i] = np.maximum(per[0],state)[i]
    per[3][0] +=1
  else:
    for i in range(len(state)):
        per[1][i] = np.minimum(per[1],state)[i]
        per[2][i] = np.maximum(per[2],state)[i]
  # Create an array of -1,0,-1
  if getReward(state) == 1 :
    per[4][0] += 1
    if per[4][0]> 100 and per[4][0]<9900:

      for i in range(len(state)):
        per[0][i] = state[i]
      for i in range(len(state)):
        per[0][i] = per[1][i]
        if getReward(per[0]) <= 0 :
          per[5][i] -= 1
        per[0][i] = per[2][i]
        if getReward(per[0]) <= 0 :
          per[5][i] -= 1
        per[0][i] = state[i]
        
  elif getReward(state) == 0 :
    per[4][0] += 1
    if per[4][0]> 100 and per[4][0]<9900:

      for i in range(len(state)):
        per[0][i] = state[i]
      for i in range(len(state)):
        per[0][i] = per[1][i]
        if getReward(per[0]) == 1 :
          per[5][i] += 1
        per[0][i] = per[2][i]
        if getReward(per[0]) == 1  :
          per[5][i] += 1
        per[0][i] = state[i]
  # Change the value of array to 1 or -1
  if per[4][0]> 100 and per[4][0]<9900:
    for i in range(len(state)):
      if per[5][i]!=0:
        per[5][i] = per[5][i] / np.abs(per[5][i])
  
  if getReward(state) != -1:
    if  per[4][0] > 100 and per[4][0] < 9900 :
 # Save the number of time each index which value is 1 or -1 get max or min 
      for i in range(len(state)):
        if per[5][i] == 1 or per[5][i] == -1: 
          if per[1][i] == state[i]  or per[2][i] == state[i]:
            per[7][i] += 1  

 # Save the total reward of state*value in 100 game only
    if per[4][0]>= 9900 :
      k = int(np.sum(per[7]))
      array_mul = (per[7]*per[5])
#Save the array with range from -1 to 1 
      for i in range(len(state)):
        per[8][i] =  array_mul[i]/np.abs(k)

      for i in range(len(state)):
        per[6][i] += (per[8][i]*state[i])
            

  return action,per

#0 biểu diễn state quá khứ
#1 biểu diễn minmum của state 
#2 biểu diễn maximum của state
#3 biểu diễn trigger
#4 biểu diễn số trận chơi
#5 array chỉ có 1,0,-1
#6 biểu diễn tổng thưởng của state*value trong 100 trận
#7 biểu diễn số lần các index 1,-1,0 xuất hiện
#8 array giá trị từ -1 đến 1


perx = [np.zeros(getStateSize()),np.zeros(getStateSize()),np.zeros(getStateSize()),np.zeros(getStateSize()),np.zeros(getStateSize()),np.zeros(getStateSize()),np.zeros(getStateSize()),np.zeros(getStateSize()),np.zeros(getStateSize())]

          #0                            #1                       #2                       #3                      #4                          #5                    #6.                       #7                          #8
win, x = numba_main_2(p0,  10000,perx ,0)
print(win)

2652


In [98]:
print(perx[5])

[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1.
  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
  0.  0.  0.  0.  0.  0.  0.  0.  0. -1. -1. -1.  0.  0.  0.  0.  0.]


In [99]:
print(perx[5])

[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1.
  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
  0.  0.  0.  0.  0.  0.  0.  0.  0. -1. -1. -1.  0.  0.  0.  0.  0.]


In [95]:
print(perx[7]*perx[5])

[  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
   0.   0.   0.  14.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0. -11.
 -11. -19.   0.   0.   0.   0.   0.]


In [81]:
print(((perx[8]))!=0)

[False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False  True  True  True
 False False False False False]


In [18]:
print(perx[6])

[    0.             0.             0.             0.
     0.             0.             0.             0.
     0.             0.             0.             0.
     0.             0.             0.             0.
     0.         -1208.             0.             0.
     0.             0.             0.             0.
     0.             0.             0.             0.
     0.             0.             0.             0.
     0.             0.             0.             0.
     0.             0.             0.             0.
     0.             0.             0.             0.
     0.             0.             0.             0.
     0.             0.             0.             0.
     0.             0.             0.             0.
     0.             0.             0.             0.
     0.             0.             0.             0.
     0.             0.             0.             0.
     0.             0.             0.             0.
     0.             0.             0.         

In [8]:
# Biếu diện tổng thưởng của state*value chia số trận
print(np.sum(x[6])/100)


-23.25


# Check tất cả các game bài tập 2 




**Check Game Splendor_v3**

In [ ]:
import numpy as np
from base.Splendor_v3.env import *

perx = [np.full(getStateSize(),0),np.full(getStateSize(),0),np.full(getStateSize(),0),np.full(getStateSize(),0),np.full(getStateSize(),0),np.full(getStateSize(),0),np.full(getStateSize(),0),np.full(getStateSize(),0),np.full(getStateSize(),0)]

          #0                            #1                       #2                       #3                      #4                          #5                    #6.                       #7                          #8
win, x = numba_main_2(p0,  10000,perx ,0)
print(win)
# Print the sum of state*value
print(np.sum(x[6])/100)


1280


 **Check game TLMN_v2**

In [ ]:
import numpy as np
from base.TLMN_v2.env import *
perx = [np.full(getStateSize(),0),np.full(getStateSize(),0),np.full(getStateSize(),0),np.full(getStateSize(),0),np.full(getStateSize(),0),np.full(getStateSize(),0),np.full(getStateSize(),0),np.full(getStateSize(),0),np.full(getStateSize(),0)]

          #0                            #1                       #2                       #3                      #4                          #5                    #6.                       #7                          #8
win, x = numba_main_2(p0,  10000,perx ,0)
print(win)
# Print the sum of state*value
print(np.sum(x[6])/100)


2521


**Check Game TLMN**

In [ ]:
import numpy as np
from base.TLMN.env import *
perx = [np.full(getStateSize(),0),np.full(getStateSize(),0),np.full(getStateSize(),0),np.full(getStateSize(),0),np.full(getStateSize(),0),np.full(getStateSize(),0),np.full(getStateSize(),0),np.full(getStateSize(),0),np.full(getStateSize(),0)]

          #0                            #1                       #2                       #3                      #4                          #5                    #6.                       #7                          #8
win, x = numba_main_2(p0,  10000,perx ,0)
print(win)
# Print the sum of state*value
print(np.sum(x[6])/100)


12319


**Check Game SushiGO**

In [ ]:
import numpy as np
from base.SushiGo.env import *
perx = [np.full(getStateSize(),0),np.full(getStateSize(),0),np.full(getStateSize(),0),np.full(getStateSize(),0),np.full(getStateSize(),0),np.full(getStateSize(),0),np.full(getStateSize(),0),np.full(getStateSize(),0),np.full(getStateSize(),0)]

          #0                            #1                       #2                       #3                      #4                          #5                    #6.                       #7                          #8
win, x = numba_main_2(p0,  10000,perx ,0)
print(win)
# Print the sum of state*value
print(np.sum(x[6])/100)


: 

: 

**Check MachiKoro**

In [ ]:
import numpy as np
from base.MachiKoro.env import *
perx = [np.full(getStateSize(),0),np.full(getStateSize(),0),np.full(getStateSize(),0),np.full(getStateSize(),0),np.full(getStateSize(),0),np.full(getStateSize(),0),np.full(getStateSize(),0),np.full(getStateSize(),0),np.full(getStateSize(),0)]

          #0                            #1                       #2                       #3                      #4                          #5                    #6.                       #7                          #8
win, x = numba_main_2(p0,  10000,perx ,0)
print(win)
# Print the sum of state*value
print(np.sum(x[6])/100)


2515


**Check Game Splendor**

In [ ]:
import numpy as np
from base.Splendor.env import *
perx = [np.full(getStateSize(),0),np.full(getStateSize(),0),np.full(getStateSize(),0),np.full(getStateSize(),0),np.full(getStateSize(),0),np.full(getStateSize(),0),np.full(getStateSize(),0),np.full(getStateSize(),0),np.full(getStateSize(),0)]

          #0                            #1                       #2                       #3                      #4                          #5                    #6.                       #7                          #8
win, x = numba_main_2(p0,  10000,perx ,0)
print(win)
# Print the sum of state*value
print(np.sum(x[6])/100)


**Check Game Splendor_v2**

In [ ]:
import numpy as np
from base.Splendor_v2.env import *
perx = [np.full(getStateSize(),0),np.full(getStateSize(),0),np.full(getStateSize(),0),np.full(getStateSize(),0),np.full(getStateSize(),0),np.full(getStateSize(),0),np.full(getStateSize(),0),np.full(getStateSize(),0),np.full(getStateSize(),0)]

          #0                            #1                       #2                       #3                      #4                          #5                    #6.                       #7                          #8
win, x = numba_main_2(p0,  10000,perx ,0)
print(win)
# Print the sum of state*value
print(np.sum(x[6])/100)


**Check Game Sheriff**

In [ ]:
import numpy as np
from base.Sheriff.env import *
perx = [np.full(getStateSize(),0),np.full(getStateSize(),0),np.full(getStateSize(),0),np.full(getStateSize(),0),np.full(getStateSize(),0),np.full(getStateSize(),0),np.full(getStateSize(),0),np.full(getStateSize(),0),np.full(getStateSize(),0)]

          #0                            #1                       #2                       #3                      #4                          #5                    #6.                       #7                          #8
win, x = numba_main_2(p0,  10000,perx ,0)
print(win)
# Print the sum of state*value
print(np.sum(x[6])/100)


**Check Game Century**

In [ ]:
import numpy as np
from base.Century.env import *
perx = [np.full(getStateSize(),0),np.full(getStateSize(),0),np.full(getStateSize(),0),np.full(getStateSize(),0),np.full(getStateSize(),0),np.full(getStateSize(),0),np.full(getStateSize(),0),np.full(getStateSize(),0),np.full(getStateSize(),0)]

          #0                            #1                       #2                       #3                      #4                          #5                    #6.                       #7                          #8
win, x = numba_main_2(p0,  10000,perx ,0)
print(win)
# Print the sum of state*value
print(np.sum(x[6])/100)
