# Bài tập 1 
Hoàn thiện bot để có tỷ lệ thắng trên 90 %

In [1]:
%cd /Users/trancatkhanh/Downloads/GAME
from base.Splendor_v3.env import *


/Users/trancatkhanh/Downloads/GAME


In [5]:
import numpy as np
from numba import njit 
#Khởi tạo weight 
perx = [np.zeros((60,getStateSize())),np.zeros((12,60))]
for i in range(0,12):
    for j in range(5):
        perx[0][i*5+j][6+j] = 1
        perx[0][i*5+j][11] = 0 
        perx[0][i*5+j][12+j] = 1
        perx[0][i*5+j][20+i*7+j] = -1
for i in range(0,12):
    for j in range(5):
        perx[1][i][i*5+j] = 1

print(np.sum(perx[0]))

60.0


In [12]:
from base.Splendor_v3.env import *
@njit
def p0(state,per):
    actions = getValidActions(state)
    matran1 = per[0]@state
    for i in range(len(matran1)):
        matran1[i] = int(matran1[i] >= 0)
    matran2 = per[1]@matran1
    matran2 *= actions
    action = np.argmax(matran2)
    return action,per
win, x = numba_main_2(p0, 10000,perx,0)


[1. 3. 4. 1. 4. 4. 2. 2. 4. 2. 3. 2.]
[2. 4. 4. 2. 4. 4. 2. 2. 4. 2. 3. 2.]
[2. 5. 4. 3. 4. 4. 2. 3. 4. 2. 3. 2.]
[3. 4. 2. 4. 4. 4. 2. 2. 4. 2. 3. 2.]
[4. 2. 5. 3. 4. 4. 3. 2. 4. 2. 3. 2.]
[4. 2. 3. 3. 3. 2. 2. 4. 4. 2. 3. 2.]
[4. 3. 4. 4. 3. 2. 2. 4. 2. 3. 2. 4.]
[4. 4. 4. 4. 3. 3. 4. 3. 3. 3. 3. 4.]
[5. 4. 4. 4. 3. 4. 4. 4. 3. 3. 3. 4.]
[4. 4. 3. 4. 2. 3. 4. 3. 3. 3. 3. 4.]
[4. 3. 4. 5. 2. 3. 3. 3. 3. 3. 4. 3.]
[4. 3. 3. 3. 3. 3. 2. 4. 3. 3. 4. 3.]
[3. 4. 4. 3. 2. 3. 3. 4. 3. 4. 3. 1.]
[4. 4. 4. 4. 4. 4. 3. 4. 3. 3. 3. 2.]
[5. 4. 5. 5. 4. 4. 3. 4. 3. 3. 3. 2.]
[4. 5. 5. 5. 3. 3. 2. 4. 3. 3. 2. 2.]
[4. 4. 4. 5. 3. 3. 2. 4. 3. 3. 3. 2.]
[4. 4. 4. 5. 3. 3. 3. 4. 3. 3. 3. 2.]
[4. 4. 4. 5. 4. 3. 4. 4. 3. 3. 3. 2.]
[5. 5. 4. 4. 4. 3. 4. 4. 3. 3. 2. 4.]
[5. 4. 5. 5. 4. 3. 4. 4. 3. 4. 4. 4.]
[4. 5. 5. 4. 4. 3. 4. 4. 3. 4. 4. 4.]
[4. 5. 5. 5. 3. 4. 4. 5. 3. 4. 4. 4.]
[5. 5. 5. 4. 5. 4. 5. 4. 4. 4. 4. 0.]
[5. 5. 5. 4. 5. 4. 5. 4. 4. 0. 0. 0.]
[5. 5. 4. 4. 4. 4. 4. 4. 0. 0. 0. 0.]
[4. 4. 5. 5.

In [10]:
print('tỷ lệ thắng',(win/10000)*100)

tỷ lệ thắng 92.31


# Bài tập 2 : Tính tỷ lệ thắng của Bot có weight feature tìm tay
**==> Tỷ lệ thắng của bot có weight feature đánh mình action 0 là 40.6%**


**==> Tỷ lệ thắng của bot có weight feature đánh mình action 1 là 46,97%**

In [ ]:
import numpy as np
from numba import njit 
for k in range(0,15):
    #Khởi tạo weight 
    perx = [np.zeros((5,getStateSize())),np.zeros((1,5))]
    for i in range(1):
        for j in range(5):
            perx[0][i*5+j][6+j] = 1
            perx[0][i*5+j][11] = 0 
            perx[0][i*5+j][12+j] = 1
            perx[0][i*5+j][20+k*7+j] = -1
    perx[1][0:6]=1
    from base.Splendor_v3.env import *

    @njit
    def p0(state,per):
        actions = getValidActions(state)
        actions = np.where(actions == 1)[0]
        matran1 = per[0]@state
        for i in range(len(matran1)):
            matran1[i] = int(matran1[i] >= 0)
        matran2 = per[1]@matran1
        # matran2 *= actions
        if np.sum(matran2) == 5 and k in actions:
            action = k
        else:
            action = actions[np.random.randint(len(actions))]
        return action,per
        
    win, x = numba_main_2(p0, 1000,perx,0)
    print('tỷ lệ thắng của action'+f'{k}',(win/1000)*100)

# Bài tập 3 : Tính tỷ lệ thắng của Bot có weight feature random
**==> Tỷ lệ thắng của bot có weight feature random đánh mình action 0 là 42.52%**


**==> Tỷ lệ thắng của bot có weight feature  random đánh mình action 1 là 47.16%**

**Cách 1** lấy cả 5 feature của thẻ đó 

In [1]:
from base.Splendor_v3.env import *
for k in range(15):
    import numpy as np
    from numba import njit 
    #Khởi tạo weight 
    perx = [np.random.randn(5,getStateSize()),np.zeros((1,5))]
    for i in range(0,5):
        for j in range(getStateSize()):
            if perx[0][i][j] > np.random.randn(1):
                perx[0][i][j] = 1
            elif perx[0][i][j] < np.random.randn(1):
                perx[0][i][j] =  0
            else:
                perx[0][i][j] = -1
    perx[1][0:6]=1

    @njit
    def p0(state,per):
        actions = getValidActions(state)
        matran1 = per[0]@state
        for i in range(len(matran1)):
            matran1[i] = int(matran1[i] >= 0)
        matran2 = per[1]@matran1
        matran2 *= actions
        if matran2 == 5 :
            action = k
        else:
            actions = np.where(actions == 1)[0]
            action = actions[np.random.randint(len(actions))]
            while action == k:
                action = actions[np.random.randint(len(actions))]
        return action,per
        
    win, x = numba_main_2(p0, 1000,perx,0)
    print('tỷ lệ thắng',(win/1000)*100)

ModuleNotFoundError: No module named 'base'

**Cách 2** chỉ cần 3 feature đặc biệt 

In [7]:
import numpy as np
from numba import njit 
#Khởi tạo weight 
perx = [np.random.randn(3,getStateSize()),np.zeros((1,3))]
for i in range(0,3):
    for j in range(getStateSize()):
        if perx[0][i][j] > np.random.randn(1):
            perx[0][i][j] = 1
        elif perx[0][i][j] < np.random.randn(1):
            perx[0][i][j] =  0
        else:
            perx[0][i][j] = -1
# for i in range(0,5):
#     for j in range(5):
#         if perx[1][i][j] > np.random.randn(1):
#             perx[1][i][j] = 1
#         elif perx[1][i][j] < np.random.randn(1):
#             perx[1][i][j] =  0
#         else:
#             perx[1][i][j] = -1
perx[1][0:4]=1
from base.Splendor_v3.env import *
@njit
def p0(state,per):
    actions = getValidActions(state)
    matran1 = per[0]@state
    for i in range(len(matran1)):
        matran1[i] = int(matran1[i] >= 0)
    matran2 = per[1]@matran1

    matran2 *= actions
    if matran2 == 3 :
        action = 0 
    else:
        actions = np.where(actions == 1)[0]
        action = actions[np.random.randint(len(actions))]
    return action,per
win, x = numba_main_2(p0, 10000,perx,0)
print('tỷ lệ thắng',(win/10000)*100)

tỷ lệ thắng 41.15
